### ISSUE TITLE
distribution *might* be important, refactor in rust or go?

### ISSUE THREAD

**Issue by tomlue** [sysrev/srvc#8]

**Comment by john-shaffer** [comment]
This is probably the simplest solution for both speed and distribution.

Our key libraries:
* Go:
 * https://pkg.go.dev/github.com/gibson042/canonicaljson-go
 * https://github.com/multiformats/go-multihash
* Rust:
 * https://github.com/mozilla-services/canonicaljson-rs
 * https://github.com/multiformats/rust-multihash

**Comment by john-shaffer** [comment]
Cross-compiling the clojure code looks to be a long ways out: https://github.com/oracle/graal/issues/1446
