### ISSUE TITLE
The installation directions must be incomplete

### ISSUE THREAD

**Issue by jkitchin** [sysrev/srvc#9]
In `ln -s $(pwd)/mvp-bb/sr.clj /usr/local/bin/sr # add to path`

where is mvp-bb? there doesn't seem to be a sr.clj in the repo. are there some other build commands?

**Comment by tomlue** [comment]
Apologies, we should update this repo to point to https://github.com/insilica/rs-srvc. 

Originally srvc was written in clojure, but we moved to rust.

**Comment by tomlue** [comment]
I have updated the readme to point to [rs-srvc](https://github.com/insilica/rs-srvc). We may eventually move rs-srvc to this repo as well, but for now I am closing this issue.
